---
title: "IMMERSE Training Notes"
author: "Nathan Alexander"
institute: 
  - "Howard University"
  - "Center for Applied Data Science and Analytics"
format: html
---

## Pre-training Day 1

No relevant coding notes.

## Pre-training Day 2

### Set-up

```{r}
#| echo: false
#| output: false
#| warning: false

# install.packages("tidyverse", repos = "http://cran.us.r-project.org")
# install.packages("palmerpenguins", repos = "http://cran.us.r-project.org")

library(tidyverse)
library(palmerpenguins)
library(ggplot2)
data(penguins) # load data
df <- penguins
```

#### Load palmer penguins data

```{r}
#| echo: true
#| output: true
#| warning: false
glimpse(df) # get a glimpse of the data
dim(df) # gather the dimensions of the data
names(df) # gather names of variables
summary(df) # gather a summary of the data

```

#### Create a graph using ggplot

Steps to create plot

  1. ggplot()
  
  2. Data, variable `x`, and variable `y`
  
  3. What type of graph?
  
```{r}
#| echo: true
#| output: true
#| warning: false

ggplot(data = df, aes(x = flipper_length_mm, y = body_mass_g)) +
  geom_point()

```

